version: "3.9"
services: 
    # MySQL
    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports:
        - 3307:3306
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
        MYSQL_DATABASE: ez_musix    
    app:
      container_name: api_ezmusix
      build: .
      restart: always
      ports: 
        - 8000:8000
      volumes:
        - .:/usr/src/app/